#!/bin/bash
# echo "PATH=$PATH"
# export PATH=/I/Dev/Qt/Tools/CMake_64/bin:$PATH
# export CMAKE_PREFIX_PATH=I:/Dev/Qt/6.5.0/android_arm64_v8a/lib/cmake/Qt6
# export QT_DIR=I:/Dev/Qt/6.5.0/
#CMAKE_MODULE_PATH: I:/Dev/Qt/6.5.0/android_arm64_v8a/lib/cmake/Qt6/platforms

# I:\Dev\Qt\Tools\CMake_64\bin\cmake.exe -S C:/Users/skoro/Projects/vocabulary/QtGUI -B C:/Users/skoro/Projects/vocabulary/build-QtGUI-Android_Qt_6_5_0_Clang_arm64_v8a-Debug "-DCMAKE_GENERATOR:STRING=Ninja" "-DCMAKE_BUILD_TYPE:STRING=Debug" "-DCMAKE_PROJECT_INCLUDE_BEFORE:FILEPATH=C:\Users\skoro\Projects\vocabulary\build-QtGUI-Android_Qt_6_5_0_Clang_arm64_v8a-Debug/.qtc/package-manager/auto-setup.cmake" "-DQT_QMAKE_EXECUTABLE:FILEPATH=" "-DCMAKE_PREFIX_PATH:PATH=I:/Dev/Qt/6.5.0/android_arm64_v8a/lib/cmake" "-DCMAKE_C_COMPILER:FILEPATH=" "-DCMAKE_CXX_COMPILER:FILEPATH=" "-DANDROID_PLATFORM:STRING=android-23" "-DANDROID_NDK:PATH=D:/Content/android-sdk/ndk/25.1.8937393" "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=D:/Content/android-sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake" "-DANDROID_USE_LEGACY_TOOLCHAIN_FILE:BOOL=OFF" "-DANDROID_ABI:STRING=arm64-v8a" "-DANDROID_STL:STRING=c++_shared" "-DCMAKE_FIND_ROOT_PATH:PATH=" "-DQT_NO_GLOBAL_APK_TARGET_PART_OF_ALL:BOOL=ON" "-DQT_HOST_PATH:PATH=" "-DANDROID_SDK_ROOT:PATH=D:/Content/android-sdk" "-DCMAKE_CXX_FLAGS_INIT:STRING=" in C:\Users\skoro\Projects\vocabulary\build-QtGUI-Android_Qt_6_5_0_Clang_arm64_v8a-Debug.

rm -rf ../Build-qt-cmake

/I/Dev/Qt/Tools/CMake_64/bin/cmake.exe -S .. -B ../Build-qt-cmake -DCMAKE_GENERATOR:STRING=Ninja "-DANDROID_PLATFORM:STRING=android-23" "-DANDROID_NDK:PATH=D:/Content/android-sdk/ndk/25.1.8937393" "-DQT_CHAINLOAD_TOOLCHAIN_FILE:FILEPATH=D:/Content/android-sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake" "-DANDROID_USE_LEGACY_TOOLCHAIN_FILE:BOOL=OFF" "-DANDROID_ABI:STRING=arm64-v8a" "-DANDROID_STL:STRING=c++_shared"  "-DQT_NO_GLOBAL_APK_TARGET_PART_OF_ALL:BOOL=ON" "-DANDROID_SDK_ROOT:PATH=D:/Content/android-sdk" -DCMAKE_MAKE_PROGRAM=/I/Dev/Qt/Tools/Ninja/ninja.exe -DCMAKE_TOOLCHAIN_FILE=I:/Dev/Qt/6.5.0/android_arm64_v8a/lib/cmake/Qt6/qt.toolchain.cmake

# I:\Dev\Qt\Tools\CMake_64\bin\cmake.exe -S C:/Users/skoro/Projects/vocabulary/QtGUI -B C:/Users/skoro/Projects/vocabulary/QtGUI/Build-cmake-android "-DCMAKE_GENERATOR:STRING=Ninja" "-DCMAKE_BUILD_TYPE:STRING=Debug" "-DCMAKE_PROJECT_INCLUDE_BEFORE:FILEPATH=C:\Users\skoro\Projects\vocabulary\QtGUI\Build-cmake-android/.qtc/package-manager/auto-setup.cmake" "-DQT_QMAKE_EXECUTABLE:FILEPATH=" "-DCMAKE_PREFIX_PATH:PATH=I:/Dev/Qt/6.5.0/android_arm64_v8a/lib/cmake" "-DCMAKE_C_COMPILER:FILEPATH=" "-DCMAKE_CXX_COMPILER:FILEPATH=" "-DANDROID_PLATFORM:STRING=android-23" "-DANDROID_NDK:PATH=D:/Content/android-sdk/ndk/25.1.8937393" "-DANDROID_USE_LEGACY_TOOLCHAIN_FILE:BOOL=OFF" "-DANDROID_ABI:STRING=arm64-v8a" "-DANDROID_STL:STRING=c++_shared" "-DCMAKE_FIND_ROOT_PATH:PATH=" "-DQT_NO_GLOBAL_APK_TARGET_PART_OF_ALL:BOOL=ON" "-DANDROID_SDK_ROOT:PATH=D:/Content/android-sdk" "-DCMAKE_CXX_FLAGS_INIT:STRING=" "-DQT_CHAINLOAD_TOOLCHAIN_FILE:FILEPATH=D:/Content/android-sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake" "-DQT_CHAINLOAD_TOOLCHAIN_FILE:FILEPATH=D:/Content/android-sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake" in C:\Users\skoro\Projects\vocabulary\QtGUI\Build-cmake-android.

# I:/Dev/Qt/Tools/CMake_64/bin/cmake.exe -S C:/Users/skoro/Projects/vocabulary/QtGUI -B C:/Users/skoro/Projects/vocabulary/QtGUI/Build-qt-cmake-Android -DCMAKE_MAKE_PROGRAM=/I/Dev/Qt/Tools/Ninja/ninja.exe
